-- VocaSafe Lab: authoritative QR scan safety summary and minimal scan audit.
-- Review and run manually after 010_asset_k3_operational_hardening.sql.

begin;

create table public.asset_scan_events (
  id bigint generated by default as identity primary key,
  asset_id uuid not null references public.assets(id) on delete cascade,
  laboratory_id uuid not null references public.laboratories(id) on delete cascade,
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  scan_source text not null check (scan_source in ('camera', 'manual', 'qr_link')),
  safety_decision text not null check (
    safety_decision in ('clear', 'restricted', 'blocked', 'unverified')
  ),
  scanned_at timestamptz not null default now()
);

create index idx_asset_scan_events_asset_time
  on public.asset_scan_events(asset_id, scanned_at desc);
create index idx_asset_scan_events_laboratory_time
  on public.asset_scan_events(laboratory_id, scanned_at desc);

alter table public.asset_scan_events enable row level security;

revoke all on public.asset_scan_events from anon;
revoke insert, update, delete on public.asset_scan_events from authenticated;
grant select on public.asset_scan_events to authenticated;

create policy "asset managers can read scan events"
on public.asset_scan_events
for select
to authenticated
using (public.can_manage_laboratory(asset_scan_events.laboratory_id));

create or replace function public.get_asset_scan_safety(target_asset_id uuid)
returns table (
  asset_id uuid,
  checked_at timestamptz,
  expired_certificate_count bigint,
  certificate_due_soon_count bigint,
  open_work_order_count bigint,
  failed_control_count bigint,
  open_critical_report_count bigint,
  pending_review_count bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    asset.id,
    pg_catalog.statement_timestamp(),
    (
      select pg_catalog.count(*)
      from public.asset_certificates as certificate
      where certificate.asset_id = asset.id
        and certificate.expires_at is not null
        and certificate.expires_at < pg_catalog.statement_timestamp()::date
    ),
    (
      select pg_catalog.count(*)
      from public.asset_certificates as certificate
      where certificate.asset_id = asset.id
        and certificate.expires_at is not null
        and certificate.expires_at >= pg_catalog.statement_timestamp()::date
        and certificate.expires_at <= pg_catalog.statement_timestamp()::date + 30
    ),
    (
      select pg_catalog.count(*)
      from public.asset_work_orders as work_order
      where work_order.asset_id = asset.id
        and work_order.status not in ('selesai', 'dibatalkan')
    ),
    (
      select pg_catalog.count(*)
      from public.asset_safety_controls as control
      where control.asset_id = asset.id
        and control.status = 'tidak_berfungsi'
    ),
    (
      select pg_catalog.count(*)
      from public.reports as report
      where report.asset_id = asset.id
        and report.risk_category = 'kritis'
        and report.status not in ('selesai', 'ditolak')
    ),
    (
      select pg_catalog.count(*)
      from public.asset_inspection_reviews as review
      where review.asset_id = asset.id
        and review.review_status = 'menunggu'
    )
  from public.assets as asset
  where asset.id = target_asset_id
    and public.can_access_laboratory(asset.laboratory_id);
$$;

revoke all on function public.get_asset_scan_safety(uuid) from public;
revoke all on function public.get_asset_scan_safety(uuid) from anon;
grant execute on function public.get_asset_scan_safety(uuid) to authenticated;

create or replace function public.record_asset_scan_event(
  target_asset_id uuid,
  event_scan_source text,
  event_safety_decision text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_laboratory_id uuid;
  new_event_id bigint;
begin
  if event_scan_source not in ('camera', 'manual', 'qr_link') then
    raise exception 'Sumber scan tidak valid.' using errcode = '22023';
  end if;

  if event_safety_decision not in ('clear', 'restricted', 'blocked', 'unverified') then
    raise exception 'Keputusan keselamatan tidak valid.' using errcode = '22023';
  end if;

  select asset.laboratory_id
  into target_laboratory_id
  from public.assets as asset
  where asset.id = target_asset_id;

  if target_laboratory_id is null
    or not public.can_access_laboratory(target_laboratory_id) then
    raise exception 'Aset tidak dapat diakses.' using errcode = '42501';
  end if;

  insert into public.asset_scan_events (
    asset_id,
    laboratory_id,
    user_id,
    scan_source,
    safety_decision
  ) values (
    target_asset_id,
    target_laboratory_id,
    (select auth.uid()),
    event_scan_source,
    event_safety_decision
  )
  returning id into new_event_id;

  return new_event_id;
end;
$$;

revoke all on function public.record_asset_scan_event(uuid, text, text) from public;
revoke all on function public.record_asset_scan_event(uuid, text, text) from anon;
grant execute on function public.record_asset_scan_event(uuid, text, text) to authenticated;

commit;
